require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

RSpec/FilePath:
  CustomTransform:
    AdventOfCode2020: advent_of_code_2020

Style/Documentation:
  Enabled: false
