[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Matt Thomson <mattjohnthomson@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
bytecount = "0.6"
fixedbitset = "0.2"
itertools = "0.8"
num = "0.2"
pathfinding = "2.0"
permutohedron = "0.2"
structopt = "0.3"
