on: [push]

name: CI

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Read .ruby-version
        run: echo "##[set-output name=RUBY_VERSION;]$(cat .ruby-version)"
        id: ruby-version
      - uses: ruby/setup-ruby@v1.70.0
        with:
          ruby-version: "${{ steps.ruby-version.outputs.RUBY_VERSION }}"
      - name: Install dependencies
        run: bundle install
      - name: Rubocop
        run: bin/rubocop
      - name: RSpec
        run: bin/rspec
