on: [push]

name: CI

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Setup Rust toolchain
        run: rustup show
      - name: Setup just
        uses: extractions/setup-just@v1.4.0
      - name: Lint
        run: just lint
      - name: Test
        run: just test
