on: [push]

name: CI

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup Rust toolchain
        run: rustup show
      - uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --locked
